[book]
authors = ["Daehyun Kim"]
language = "ko"
multilingual = false
src = "src"
title = "hatemogi.com"
description = "백엔드 개발자 김대현의 개인 웹사이트"

[build]
build-dir = "docs"

[output.html]
additional-css = ["custom.css"]
mathjax-support = true
no-section-label = true
# git-repository-url = "https://github.com/hatemogi/2023.hatemogi.com"
# git-repository-icon = "fa-github"
# site-url = "https://hatemogi.com/"

[output.html.search]
enable = false